//ooking detail
const GET_BOOKING_DETAIL = 'GET_BOOKING_DETAIL';
const GET_BOOKING_DETAIL_FULFILLED = 'GET_BOOKING_DETAIL_FULFILLED';
const GET_BOOKING_DETAIL_PENDING = 'GET_BOOKING_DETAIL_PENDING';
const GET_BOOKING_DETAIL_REJECTED = 'GET_BOOKING_DETAIL_REJECTED';

//accommodation detail
const GET_ACCOMMODATION_DETAIL = 'GET_ACCOMMODATION_DETAIL';
const GET_ACCOMMODATION_DETAIL_FULFILLED = 'GET_ACCOMMODATION_DETAIL_FULFILLED';
const GET_ACCOMMODATION_DETAIL_PENDING = 'GET_ACCOMMODATION_DETAIL_PENDING';
const GET_ACCOMMODATION_DETAIL_REJECTED = 'GET_ACCOMMODATION_DETAIL_REJECTED';

export {
  //booking detail
  GET_BOOKING_DETAIL,
  GET_BOOKING_DETAIL_FULFILLED,
  GET_BOOKING_DETAIL_PENDING,
  GET_BOOKING_DETAIL_REJECTED,
  GET_ACCOMMODATION_DETAIL,
  GET_ACCOMMODATION_DETAIL_FULFILLED,
  GET_ACCOMMODATION_DETAIL_PENDING,
  GET_ACCOMMODATION_DETAIL_REJECTED,
};
